### PR TITLE
Update utility.lua

### PR DESCRIPTION
**Pull request by VforViolin**
Update Auxiliary.ArcanaCoinOperation to reflect Light Barrier changes

### CODE REVIEW

**Comment by salix5** [comment]
#2733

**Comment by VforViolin** [comment]
> #2733

The old Arcana Force cards arent working with the changes made in that commit to utility.lua. My proposed change fixes all of the issues with the old Arcana Force cards, and doesnt break anything with the new Arcana Force cards.

**Comment by salix5** [comment]
Are you from YGO Omega team?

**Comment by VforViolin** [comment]
Omega/Nexus, yes

**Comment by salix5** [comment]
Test 
executable built with https://github.com/Fluorohydride/ygopro-core/commit/4047c1a7d2dd6f665a11e1de798939893362d4f5
Visual Studio Community 2022 Debug Mode, current master https://github.com/Fluorohydride/ygopro-core/commit/e090c4f98447cb49daf0c800f1ca00d649ffef9e

Single script
```lua
--[[message arcana]]
Debug.SetAIName("Bug")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(62892347,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(73206827,0,0,LOCATION_HAND,1,POS_FACEDOWN)
Debug.AddCard(41587307,0,0,LOCATION_HAND,1,POS_FACEDOWN)

Debug.AddCard(89631139,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,0,0,LOCATION_GRAVE,0,POS_FACEUP_ATTACK)

Debug.AddCard(89631139,0,0,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(89631139,0,0,LOCATION_DECK,1,POS_FACEDOWN)

Debug.AddCard(89631139,1,1,LOCATION_MZONE,2,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,1,1,LOCATION_MZONE,3,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,1,1,LOCATION_MZONE,4,POS_FACEUP_ATTACK)
Debug.AddCard(89631139,1,1,LOCATION_GRAVE,0,POS_FACEUP_ATTACK)

Debug.ReloadFieldEnd()

```

Old Arcana Force cards works fine
Not reproducible


Under such circumstances, I think i need more information than "old Arcana Force cards arent working".
Please give me complete detail if you still find any problem.
Hand: ?
Field: ? 
Or write a single script to demonstrate the problem if possible.

**Comment by VforViolin** [comment]
Was this test done with the most recent core updates?

**Comment by VforViolin** [comment]
Also, incase it wasnt clear, the issue was that the old Arcana Force cards werent allowing you to select the coin toss result you wish to apply, while Light Barrier is on the field, not negated.

**Comment by salix5** [comment]
I am not sure what version do you mean by "most recent core updates"
If your executable is built by other people, please ask them about their version.

I suggest to build on your own.
https://github.com/Fluorohydride/ygopro/wiki/Building-on-Windows
mercury233 has written a complete instructions in wiki page.

**Comment by salix5** [comment]
> Was this test done with the most recent core updates?
If you mean current master of ygopro-core
https://github.com/Fluorohydride/ygopro-core/commit/e090c4f98447cb49daf0c800f1ca00d649ffef9e

Yes, the test is done on this version and it works fine.
The goal of this repository is providing scripts that works on current ygopro-core.
As far as I know, there is no problem with Arcana Force cards and Light Barrier now.

**Comment by VforViolin** [comment]
Once Omega updates their core to the current core release (last updated 4 days ago), I'll test it again there to see if the issue persists.

**Comment by salix5** [comment]
ygopro will use the script in expansions first if `prefer_expansion_script` is ON.
There might be similar settings in other version.
Please make sure that your expansions directive is empty when you test.

**Pull request closed without merging**
