### PR TITLE
fix Necrovalley and Ghost Belle

### PR DESCRIPTION
**Pull request by mercury233**
fix https://github.com/Fluorohydride/ygopro-scripts/pull/1559

For effects that target cards in grave with definite action (eg. _Monster Reborn_):
- `SetOperationInfo` with the target, without location
- Necrovalley negate them in Necrovalley's script, by checking `tg:IsExists`
- Ghost Belle negate them by checking `tg:IsExists`

For effects that target cards in grave but with not definite action (eg. _World Legacy Guardragon_):
- SetOperationInfo without the part of grave
- `SetCategory` with `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
- Use `aux.NecroValleyNegateCheck(tg)` in the script of the effect
- Ghost Belle negate them by checking `IsHasCategory(CATEGORY_GRAVE_ACTION)`

For effects that don't target but only affect 1 card in grave and won't resolve without card in grave (eg. _Salamangreat Sunlight Wolf_):
- `SetOperationInfo` with `nil` as target, with `count`>0 and `param`==`LOCATION_GRAVE` exactly
- Necrovalley negate them in Necrovalley's script, by checking `v==LOCATION_GRAVE and ct>0`
- Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`

For effects that don't target but affect cards in grave and won't resolve without card in grave (eg. _Lazion, the Timelord_):
- `SetOperationInfo` with affected cards as target, with `count`>0
- Use `aux.NecroValleyNegateCheck(g)` in the script of the effect
- Ghost Belle negate them by checking `tg:IsExists`

For effects that don't target but affect cards in grave and may resolve without card in grave (eg. _Preparation of Rites_):
- `SetOperationInfo` without the part of grave
- `SetCategory` with `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
- Use `aux.NecroValleyFilter` in the script of the effect
- Ghost Belle negate them by checking `IsHasCategory(CATEGORY_GRAVE_ACTION)`

For effects that don't target but may affect cards in grave and may resolve without card in grave (eg. _Miracle Fusion_):
- `SetOperationInfo` with `nil` as target, with `count`>0 and `param` including `LOCATION_GRAVE`
- `SetCategory` don't need `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
- Use `aux.NecroValleyFilter` in the script of the effect
- Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`

For effects that don't target but must affect cards both in grave and other place, but not including banish, and may resolve without card in grave (eg. _Localized Tornado_):
- `SetOperationInfo` with affected cards as target, with `count`>0 and `param` including `LOCATION_GRAVE`
- `SetCategory` don't need `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
- Use `aux.NecroValleyNegateCheck(g)` in the script of the effect (The effect won't resolve if it "touch" the grave)
- Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`

For effects that don't target but must banish cards both in grave and other place, and may resolve without card in grave (eg. _System Down_):
- `SetOperationInfo` with affected cards as target, with `count`>0 and `param` including `LOCATION_GRAVE`
- `SetCategory` don't need `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
- Use `aux.NecroValleyFilter` in the script of the effect (The effect will resolve because cards in grave can't be banished so it don't "touch" the grave)
- Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`

### CODE REVIEW

**Comment by salix5** [comment]
confirming

**Comment by mercury233** [comment]
> このたびの件、誠に恐れ入りますが、ご質問の状況がデュエル中に発生した際には、対戦相手の方と話し合って進めていただいたり、大会中であれば審判の判断で進めていただけましたら幸いでございます。
Q.
相手の墓地に機械族モンスターがある状態で、自分の「システム・ダウン」の発動にチェーンして相手が「メタバース」が発動したことで、「王家の眠る谷－ネクロバレー」を適用した場合、「システム・ダウン」はどのように処理を行いますか？
Q.
相手の墓地に魔法・罠カードがある状態で、自分の「水晶機巧－フェニキシオン」の①効果の発動にチェーンして相手が「メタバース」が発動したことで、「王家の眠る谷－ネクロバレー」を適用した場合、「水晶機巧－フェニキシオン」の効果はどのように処理を行いますか？
Q.
自分の墓地に「ガンドラ」モンスター３種類以上がある状態で、自分の「破壊竜ガンドラ－ギガ・レイズ」の①効果の発動にチェーンして相手が「メタバース」が発動したことで、「王家の眠る谷－ネクロバレー」を適用した場合、「破壊竜ガンドラ－ギガ・レイズ」の効果はどのように処理を行いますか？


> このたびの件、誠に恐れ入りますが、ご質問の状況がデュエル中に発生した際には、対戦相手の方と話し合って進めていただいたり、大会中であれば審判の判断で進めていただけましたら幸いでございます。
Q.
自分の墓地に「アフター・グロー」がある状態で、自分の「アフター・グロー」の発動にチェーンして相手が「メタバース」が発動したことで、「王家の眠る谷－ネクロバレー」を適用した場合、「アフター・グロー」はどのように処理を行いますか？
Q.
相手の墓地にカードがある状態で、自分の「アームド・ドラゴン・カタパルトキャノン」の②効果の発動にチェーンして相手が「メタバース」が発動したことで、「王家の眠る谷－ネクロバレー」を適用した場合、「アームド・ドラゴン・カタパルトキャノン」の効果はどのように処理を行いますか？


konami don't know about banish too

**Comment by shadowfox87** [comment]
There are rulings we can already use to determine the interaction between System Down vs Necrovalley.

> Q: While the effect of Necrovalley is applying, or if the effect of my opponent's Kycoo the Ghost Destroyer is applying, can I activate the effect of Trishula, Dragon of the Ice Barrier?

> A: In this scenario, due to the effect of your opponent's Kycoo the Ghost Destroyer (or Necrovalley), you cannot banish any cards from the Graveyard. Even in that scenario, you can activate the effect of Trishula, Dragon of the Ice Barrier, but you can only banish up to 2 of your opponent's cards (1 each from their hand and field.) Even if you banish Kycoo the Ghost Destroyer or Necrovalley on the field, you cannot banish any cards from the Graveyard.

Source: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=9670&request_locale=ja

> Q: 
Kycoo the Ghost Destroyer is face-up on my opponent's field. In this situation, can I activate System Down?

> A: While Kycoo the Ghost Destroyer is face-up on your opponent's field, you cannot banish any cards from the Graveyard. Therefore, while its effect is applying, as long as there are any Machine-Type monsters in your opponent's Graveyard, you cannot activate System Down. Note that if there aren't any Machine-Type monsters in your opponent's Graveyard, but there is at least 1 face-up Machine-Type monster on your opponent's field, you can still activate System Down.

Source: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=7649&request_locale=ja

(Here System Down cannot be activated if Necrovalley as long as there is 1 Machine-Type monster in the Graveyard.)

> Q: I activate System Down while there are Machine-Type monsters both on my opponent's side of the field and in their Graveyard. If my opponent chains Call of the Haunted and Special Summons Kycoo the Ghost Destroyer, how does the effect of System Down resolve?

> A: 
In this scenario, System Down will resolve while the effect of your opponent's Kycoo the Ghost Destroyer that prevents you from banishing any cards from the Graveyard is applying. In this case, face-up Machine-Type monsters on your opponent's field are banished normally, but those in your opponent's Graveyard are not banished.

Source: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=7815&request_locale=ja

> Q: While the effect of Necrovalley is applying, or if the effect of my opponent's Kycoo the Ghost Destroyer is applying, can I activate the effect of Nekroz of Sophia when it is Ritual Summoned?

> A: In this scenario, due to the effect of your opponent's Kycoo the Ghost Destroyer (or Necrovalley), you cannot banish any cards from the Graveyard. If there are any cards in your opponent's Graveyard, you cannot activate the effect of Nekroz of Sophia. If there are no cards in your opponent's Graveyard, you can activate the effect of Nekroz of Sophia. (The effect will be applied normally.)

Source: https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=15079&request_locale=ja

It is already clear from the above rulings what should happen. The first ruling puts Necrovalley and Kycoo in the same category. They allow Trishula to resolve its effect, banishing cards from field and hand, but not GY.
`You can banish up to 1 card each from your opponent's hand, field, and GY. (The card in the hand is chosen at random.)` Remember however that Trishula's effect is optional for choosing to banish from each location. It's not a `and if you do` or requires banishment of cards in the GY for its effect to resolve.

This is why we needed to understand how System Down works because its effect states: `banish all Machine-Type monsters your opponent controls and in their Graveyard.` Here, the effect says "and in their GY" which means it is part of the effect and not optional. The second ruling allows System Down to resolve, banishing cards from the field only, but not in the GY.

Hence, based on logic, we can deduce what happens in this scenario:
**Case 1:**
> Q: Player 1 activates System Down while there is a face-up Machine-Type monster on the field and a Machine-Type monster in the Graveyard. Player 2 chains Metaverse and activates Necrovalley from their deck. What happens?

> A: System Down will resolve, banishing the face-up Machine Type monster on the field and not banish the monster in the GY.

Notice here that Necrovalley was activated after System Down was already activated using Metaverse. This is the same thing as chaining Call of the Haunted to Special Summon Kycoo.

**Case 2:**
> Q: There is a face-up Machine-Type monster on the field and a Machine-Type monster in the Graveyard. Player 2 controls a face-up Necrovalley on the field. Can Player 1 activate System Down?

> A: Player 1 cannot activate System Down.

This case is different because Necrovalley is already face-up on the field and its effect is applying which means no cards can be banished. Therefore, System Down cannot even be activated. Proof of this is why Sophia could not activate when Necrovalley was on the field in the 3rd database ruling above.

**Comment by mercury233** [comment]
Top comment updated.

Let us assume the ruling of _System Down_ is same as  [the ruling for _Rage with Eyes of Blue_](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12596&keyword=&tag=-1&request_locale=ja)

**Comment by shadowfox87** [comment]
Case 1 is correct as per the official ruling for Rage with Eyes of Blue. I'm not sure why you crossed it out. You are only using rulings in which card effects banish. The effects that will banish will not be negated by Necrovalley. Instead, you should look at rulings that move cards from Graveyard which don't banish. Those card effects will get entirely negated.

The reason it doesn't negate stuff like System Down or Rage is because Necrovalley stops cards from being banished from grave, so it effectively stops that part of the effect. Since that part no longer applies, it shouldn't be negated.

https://db.ygorganization.com/qa#9597

> Q: 
While the effect of Necrovalley is applying, can I activate Crystron Entry?

> A: 
The effect of Crystron Entry when activated is an effect that applies to a card in the Graveyard. Even while the effect of Necrovalley is applying, you can activate Crystron Entry, but the effect is negated. (No monster is Special Summoned from either the hand or Graveyard.)

Here, you see that the entire effect of Crystron Entry is negated. This is because Crystron Entry is not banishing monsters from the Graveyard but Special Summoning it to field. It doesn't allow even the monster from hand to be Special Summoned, so the entire effect is negated. Banishing is a special case.

**Comment by mercury233** [comment]
we cant say our conjecture is correct if konami say them don't know

**Comment by shadowfox87** [comment]
When the email says don't know, then that doesn't mean the conjecture is incorrect. Our conjecture is based on official database rulings. Unless the email contradicts it, then I think it is ok. Until Konami says otherwise, this is correct.

If after merging this pull request, it abides by all current database rulings including the Crystron Entry, then I agree with this merge.

**Comment by salix5** [comment]
@mercury233 
Just to confirm some details about Necrovalley.

> 
> fix #1559
> 
> For effects that target cards in grave with definite action (eg. _Monster Reborn_):
> 
>     * `SetOperationInfo` with the target, without location
> 
>     * Necrovalley negate them in Necrovalley's script, by checking `tg:IsExists`
> 
>     * Ghost Belle negate them by checking `tg:IsExists`
> 
> 
> For effects that target cards in grave but with not definite action (eg. _World Legacy Guardragon_):
> 
>     * SetOperationInfo without the part of grave
> 
>     * `SetCategory` with `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
> 
>     * Use `aux.NecroValleyNegateCheck(tg)` in the script of the effect
> 
>     * Ghost Belle negate them by checking `IsHasCategory(CATEGORY_GRAVE_ACTION)`
> 
My opinion for _World Legacy Guardragon_:
If it targets a card, the script set operation info as usual.
Otherwise, the script does not set operation info.

It can be merged into the _Monster Reborn_ type.  


> 
> For effects that don't target but only affect 1 card in grave and won't resolve without card in grave (eg. _Salamangreat Sunlight Wolf_):
> 
>     * `SetOperationInfo` with `nil` as target, with `count`>0 and `param`==`LOCATION_GRAVE` exactly
> 
>     * Necrovalley negate them in Necrovalley's script, by checking `v==LOCATION_GRAVE and ct>0`
> 
>     * Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`
> 
> 
> For effects that don't target but affect cards in grave and won't resolve without card in grave (eg. _Lazion, the Timelord_):
> 
>     * `SetOperationInfo` with affected cards as target, with `count`>0
> 
>     * Use `aux.NecroValleyNegateCheck(g)` in the script of the effect
> 
>     * Ghost Belle negate them by checking `tg:IsExists`
Mandatory parts must move cards in grave:
It is negated by Necrovalley.


> 
> For effects that don't target but affect cards in grave and may resolve without card in grave (eg. _Preparation of Rites_):
> 
>     * `SetOperationInfo` without the part of grave
> 
>     * `SetCategory` with `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
> 
>     * Use `aux.NecroValleyFilter` in the script of the effect
> 
>     * Ghost Belle negate them by checking `IsHasCategory(CATEGORY_GRAVE_ACTION)`
> 
Optional parts will move cards in grave:
This part is not executed.

>
> For effects that don't target but may affect cards in grave and may resolve without card in grave (eg. _Miracle Fusion_):
> 
>     * `SetOperationInfo` with `nil` as target, with `count`>0 and `param` including `LOCATION_GRAVE`
> 
>     * `SetCategory` don't need `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
> 
>     * Use `aux.NecroValleyFilter` in the script of the effect
> 
>     * Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`
> 
Mandatory parts will move cards in grave or other location:
It can only move cards in other location.


> 
> For effects that don't target but must affect cards both in grave and other place, but not including banish, and may resolve without card in grave (eg. _Localized Tornado_):
> 
>     * `SetOperationInfo` with affected cards as target, with `count`>0 and `param` including `LOCATION_GRAVE`
> 
>     * `SetCategory` don't need `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
> 
>     * Use `aux.NecroValleyNegateCheck(g)` in the script of the effect (The effect won't resolve if it "touch" the grave)
> 
>     * Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`
Mandatory parts must move cards in grave:
It is negated by Necrovalley.


> 
> For effects that don't target but must banish cards both in grave and other place, and may resolve without card in grave (eg. _System Down_):
> 
>     * `SetOperationInfo` with affected cards as target, with `count`>0 and `param` including `LOCATION_GRAVE`
> 
>     * `SetCategory` don't need `CATEGORY_GRAVE_ACTION` or `CATEGORY_GRAVE_SPSUMMON`
> 
>     * Use `aux.NecroValleyFilter` in the script of the effect (The effect will resolve because cards in grave can't be banished so it don't "touch" the grave)
> 
>     * Ghost Belle negate them by checking `dv&LOCATION_GRAVE==LOCATION_GRAVE`


> 
> Let us assume the ruling of _System Down_ is same as [the ruling for _Rage with Eyes of Blue_](https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=12596&keyword=&tag=-1&request_locale=ja)

I totally agree.

Conclusion:
1. Is my understanding correct?
2. I agree with all changes but the  _World Legacy Guardragon_ type.
I think that it can be merged into the _Monster Reborn_ type.

**Comment by mercury233** [comment]
The operation of _World Legacy Guardragon_ is unknown (tohand or spsummon)
using `SetOperationInfo` may meet the problem in https://github.com/Fluorohydride/ygopro-scripts/pull/1524

**Review by salix5 — APPROVED** [review]
Thank you!

**Pull request merged**
