### PR TITLE
new card SHVI

### PR DESCRIPTION
**Pull request by nekrozar**
http://www.db.yugioh-card.com/yugiohdb/card_search.action?ope=1&sess=1&pid=1118003&rp=99999

Blue-Eyes Spirit Dragon's script is b6af9571a0ff6a0f96b54c4baaed9a71cc5da0c8

### CODE REVIEW

**Comment by Zayelion** [comment]
@nekrozar in the future please coordinate with the other scriptwriters via the ygopro-pre-scripts repository?

**Comment by nekrozar** [comment]
@Zayelion 
I didn't know about ygopro-pre-scripts.
Consider it.

**Comment by Zayelion** [comment]
> Consider it.

I don't understand.

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script
Does that mean I participate in that repository?

**Comment by StormWulf** [comment]
You're more than welcome to make commits to the repo. We would just appreciate if future pull requests focused more on the cards already committed in pre-script.

**Comment by Zayelion** [comment]
Additionally you can commit cards immediately as they are announced, and not have to do it in one major pull.

**Pull request closed without merging**
