### PR TITLE
fix for knightmare goblin's

### PR DESCRIPTION
**Pull request by AndreOliveiraMendes**
fixed a problem of knightmare crashing when using it additional normal summon.

### CODE REVIEW

**Comment by DailyShana** [comment]
Can you describe the detail situation how it crashes?

**Comment by AndreOliveiraMendes** [comment]
try to tribute summon something using knightmare goblin extra summon effect.
also there some wierd interaction with monster that tribute 3 monster.

**Comment by DailyShana** [comment]
Cannot reproduce. when advance sommon using extra summon effect, knightmare goblin cannot be used as tribute normally.

**Comment by VanillaSalt** [comment]
fixed https://github.com/Fluorohydride/ygopro/issues/2084 in https://github.com/Fluorohydride/ygopro-core/commit/8ffc49474903e22aa7bc013bdf76dccdc0d04253

**Comment by AndreOliveiraMendes** [comment]
there still problem with monster that tribute 3 monster trought :v

**Pull request closed without merging**
