### PR TITLE
update aux.AddXyzProcedureLevelFree

### PR DESCRIPTION
**Pull request by nekrozar**
Update this: _Utopic ZEXAL_ can use `AddXyzProcedureLevelFree`.

### CODE REVIEW

**Comment by mercury233** [comment]
@Smile-DK @purerosefallen can you please help me to review this?

**Comment by purerosefallen** [comment]
Merge this. This one is better than Smile's

**Comment by purerosefallen** [comment]
wait
local ct=-ft at line 498 seems not necessary

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-scripts/pull/923/commits/d66be2752e2ef1d49fec9c61aa03b87b63635e08 https://github.com/Fluorohydride/ygopro-scripts/pull/923/commits/870c01d58703bb7b78e5e655a114cca0cb87cf90 fixed.

**Comment by mercury233** [comment]
image

If 1 希望皇ホープ is on field, FNo.0 can be summoned with No. monsters.

**Comment by nekrozar** [comment]
@mercury233 Thank you for fix!

**Pull request merged**
