### PR TITLE
Vee4 patch 1

### PR DESCRIPTION
**Pull request by VforViolin**
Fixed so the effect does not trigger if it changes control before the chain in which the trigger effect would meet its activation conditions.

### CODE REVIEW

**Comment by mercury233** [comment]
any ruling?

**Comment by VforViolin** [comment]
https://db.ygoresources.com/qa#23484

**Comment by VforViolin** [comment]
This should also apply to most trigger effects that rely on an action being taken by a player, but control is shifted before the chain where the trigger would be met solves.

**Comment by salix5** [comment]
https://ocg-rule.readthedocs.io/zh-cn/latest/c03/%E8%AF%B1%E5%8F%91%E7%B1%BB%E6%95%88%E6%9E%9C.html#id28
> 「[假面英雄 暗爪](https://ygocdb.com/card/name/%E5%81%87%E9%9D%A2%E8%8B%B1%E9%9B%84%20%E6%9A%97%E7%88%AA)」等，在发动条件中记述了『自己』『对方』的效果，在连锁处理中满足发动条件，之后控制权转移的场合，另1个玩家并不满足发动条件，结果不能发动。

https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=21045&request_locale=ja
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=23484&request_locale=ja

**Comment by VforViolin** [comment]
Yes, both rulings support this commit. This also applies to Imsety, Duamutef, Quebesenuef, and Hapi, along with several other cards too, though for the Horus monsters I had to use 
`SetCode(EVENT_CUSTOM+id)`
and
`aux.RegisterMergedDelayedEvent(c,id,EVENT_LEAVE_FIELD)`
to get the same result

**Comment by salix5** [comment]
confirming
related PR: #2480

**Comment by salix5** [comment]
2a6ce7741e2e2530d25d4ee9cff710bf80e661a2

Test replay:
```lua
--[[message bug_test]]
Debug.SetAIName("Test")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)

Debug.AddCard(32909498,0,0,LOCATION_HAND,0,POS_FACEDOWN)
Debug.AddCard(72270339,0,0,LOCATION_HAND,1,POS_FACEDOWN)

Debug.AddCard(98777036,0,0,LOCATION_MZONE,0,POS_FACEUP_ATTACK)
Debug.AddCard(97077563,0,0,LOCATION_SZONE,0,POS_FACEDOWN)
Debug.AddCard(98045062,0,0,LOCATION_SZONE,1,POS_FACEDOWN)

Debug.AddCard(66570171,0,0,LOCATION_DECK,0,POS_FACEDOWN)
Debug.AddCard(40044918,0,0,LOCATION_DECK,1,POS_FACEDOWN)
Debug.AddCard(66570171,0,0,LOCATION_DECK,2,POS_FACEDOWN)
Debug.AddCard(32909498,0,0,LOCATION_GRAVE,0,POS_FACEUP_ATTACK)

Debug.AddCard(32909498,1,1,LOCATION_MZONE,0,POS_FACEUP_ATTACK)
Debug.AddCard(9634146,1,1,LOCATION_MZONE,1,POS_FACEUP_ATTACK)

Debug.ReloadFieldEnd()

```

EVENT_CHAINING+EFFECT_FLAG_DELAY
It means that `Kashtira Fenrir` must be on the filed when the monster effect is activated.
If the code is changed into EVENT_CHAIN_SOLVED, it will not work.

**Comment by VforViolin** [comment]
Well, Ive already got the script with it changed to "EVENT_CHAIN_SOLVED" set up for both Dueling Nexus and YGO Omega, and it works fine without any issues, and doesnt allow the trigger effect to activate if Fenrir changes control before the end of the chain.

**Comment by salix5** [comment]
Did you test

Field of A: Monster X
Field of B: Call of the Haunted
GY of B: Fennir

CL1: A, X
CL2: B, Call of the Haunted (target: Fennir)

Test:
The single play above
ocgcore@master

in branch VforViolin-Vee4-Patch-1
B can activate the effect of Fennir.
But he shouldn't.

**Comment by VforViolin** [comment]
I'll have to test it later today.

**Comment by VforViolin** [comment]
Ive confirmed that the situation you listed above does allow Fenrir to trigger

**Comment by salix5** [comment]
Thank you.

**Comment by Lyris12** [comment]
fixed at #2609

**Pull request closed without merging**
