### PR TITLE
fix special summon that is treated as fusion summon

### PR DESCRIPTION
**Pull request by mallu11**
`c:SetMaterial(nil)` doesn't work.

### CODE REVIEW

**Comment by mercury233** [comment]
don't work for which card?

**Comment by mallu11** [comment]
> don't work for which card?

the `Lyrilusc - Independent Nightingale`.
(1)use `Polymerization` to fusion summon it.
(2)use `Compulsory Evacuation Device` to return it to extra deck.
(3)use `Instant Fusion` to summon it, it can activate its first effect.

**Comment by mallu11** [comment]
there are other cards should be changed.

**Comment by mercury233** [comment]
any replay? isn't it a bug of the bird?

**Comment by edo9300** [comment]
Are you sure about set material not working with nil?
```
int32 scriptlib::card_set_material(lua_State *L) {
	check_param_count(L, 2);
	check_param(L, PARAM_TYPE_CARD, 1);
	card* pcard = *(card**) lua_touserdata(L, 1);
	if(!lua_isnil(L, 2)) {
		check_param(L, PARAM_TYPE_GROUP, 2);
		group* pgroup = *(group**) lua_touserdata(L, 2);
		pcard->set_material(&pgroup->container);
	} else
		pcard->set_material(0);
	return 0;
}```
It should work properly with both the parameter being nil and with no parameters at all

**Comment by mallu11** [comment]
> Are you sure about set material not working with nil?
> 
> ```
> int32 scriptlib::card_set_material(lua_State *L) {
> 	check_param_count(L, 2);
> 	check_param(L, PARAM_TYPE_CARD, 1);
> 	card* pcard = *(card**) lua_touserdata(L, 1);
> 	if(!lua_isnil(L, 2)) {
> 		check_param(L, PARAM_TYPE_GROUP, 2);
> 		group* pgroup = *(group**) lua_touserdata(L, 2);
> 		pcard->set_material(&pgroup->container);
> 	} else
> 		pcard->set_material(0);
> 	return 0;
> }
> ```
> 
> It should work properly with both the parameter being nil and with no parameters at all

in fact, the setmaterial(nil) works properly, but the `EFFECT_MATERIAL_CHECK` works incorrect when the parameter is nil. So we can change it to setmaterial(Group.CreateGroup()) or fix the `EFFECT_MATERIAL_CHECK`.

**Comment by edo9300** [comment]
> > Are you sure about set material not working with nil?
> > ```
> > int32 scriptlib::card_set_material(lua_State *L) {
> > 	check_param_count(L, 2);
> > 	check_param(L, PARAM_TYPE_CARD, 1);
> > 	card* pcard = *(card**) lua_touserdata(L, 1);
> > 	if(!lua_isnil(L, 2)) {
> > 		check_param(L, PARAM_TYPE_GROUP, 2);
> > 		group* pgroup = *(group**) lua_touserdata(L, 2);
> > 		pcard->set_material(&pgroup->container);
> > 	} else
> > 		pcard->set_material(0);
> > 	return 0;
> > }
> > ```
> > 
> > 
> > It should work properly with both the parameter being nil and with no parameters at all
> 
> in fact, the setmaterial(nil) works properly, but the `EFFECT_MATERIAL_CHECK` works incorrect when the parameter is nil. So we can change it to setmaterial(Group.CreateGroup()) or fix the `EFFECT_MATERIAL_CHECK`.

then the change should be made in set material, making it always call `EFFECT_MATERIAL_CHECK`, rather than changing it on the scripts

**Comment by mallu11** [comment]
> > > Are you sure about set material not working with nil?
> > > ```
> > > int32 scriptlib::card_set_material(lua_State *L) {
> > > 	check_param_count(L, 2);
> > > 	check_param(L, PARAM_TYPE_CARD, 1);
> > > 	card* pcard = *(card**) lua_touserdata(L, 1);
> > > 	if(!lua_isnil(L, 2)) {
> > > 		check_param(L, PARAM_TYPE_GROUP, 2);
> > > 		group* pgroup = *(group**) lua_touserdata(L, 2);
> > > 		pcard->set_material(&pgroup->container);
> > > 	} else
> > > 		pcard->set_material(0);
> > > 	return 0;
> > > }
> > > ```
> > > 
> > > 
> > > It should work properly with both the parameter being nil and with no parameters at all
> > 
> > 
> > in fact, the setmaterial(nil) works properly, but the `EFFECT_MATERIAL_CHECK` works incorrect when the parameter is nil. So we can change it to setmaterial(Group.CreateGroup()) or fix the `EFFECT_MATERIAL_CHECK`.
> 
> then the change should be made in set material, making it always call `EFFECT_MATERIAL_CHECK`, rather than changing it on the scripts. Or change the script of the lyrilusc, so that it won't allow you to trigger the effect.

well, changing the setmaterial to make it always call `EFFECT_MATERIAL_CHECK` is better than changing the script of lyrilusc.

**Pull request closed without merging**
