### PR TITLE
fix Odd-Eyes Persona Dragon

### PR DESCRIPTION
**Pull request by nekrozar**
Fix this:
- Player can target Normal Monster by Persona Dragon's effect.
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=4&cid=12480
■モンスターゾーンに表側表示で存在する、エクストラデッキから特殊召喚されているモンスター1体を対象に取る効果です。（通常モンスターを対象に選択する事はできません。）

- If you activated a card or effect that targets a odd-eyes monster you control, Persona Dragon activate Pendulum Effect.

### CODE REVIEW

**Comment by mercury233** [comment]
http://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=18573&keyword=&tag=-1
Will this ruling be in effect if this change is applicated?

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-scripts/pull/319/commits/dfce7cb24fb1995f562ed478756e5bb8be4f8b75 fixed.

**Comment by mercury233** [comment]
It works, but I want to know why not use EVENT_BECOME_TARGET..

**Comment by nekrozar** [comment]
Because, if EVENT_BECOME_TARGET was used, that problem didn't resolve.

**Comment by DailyShana** [comment]
fixed in fd2da4d85a70c3bde7227662ce38d1ddd81c9428
If chain 1 opponent target Odd Eyes monster, chain 2 change target to a non-"Odd Eyes" monster, chain 3 Tachyon Transmigration negates the activation of chain 1 but not chain 2, the effect of Odd-Eyes Persona Dragon should not be activated in the end phase, although at present there is no eligible card in OCG whose effect is changing target but cannot be negated by Tachyon Transmigration.

**Comment by nekrozar** [comment]
@DailyShana Thank you for fix!

**Pull request closed without merging**
