### PR TITLE
fix センサー万別

### PR DESCRIPTION
**Pull request by mercury233**
fix: if the race of monsters are changed to the same, this card will still keep them

### CODE REVIEW

**Comment by salix5** [comment]
i=0, 1, 2, 3
i=0, onlynew=true, p=0
It assumes that c24207889[p] is legal, and select cards based on c24207889[p].

i=1, onlynew=false, p=0
i=2, onlynew=true, p=1
i=3, onlynew=false, p=1

I think we should check c24207889[p] first to make sure that it is legal.

**Comment by mercury233** [comment]
`c24207889[p]` is always a group, as set in global check

**Comment by mercury233** [comment]
the problem is if _Reprodocus_ change a monster to dinosaur, should the player can select _Reprodocus_ to send to grave, or the new dinosaur must be sent to grave

**Comment by salix5** [comment]
https://www.db.yugioh-card.com/yugiohdb/faq_search.action?ope=5&fid=8763&keyword=&tag=-1
According to this question, I think the monster that is changed to new race should be sent to grave.

**Comment by mercury233** [comment]
in that case we should record each race monster: https://github.com/Fluorohydride/ygopro-scripts/pull/1608

but i think we still need ruling

**Pull request closed without merging**
