### PR TITLE
add EFFECT_TUNER

### PR DESCRIPTION
**Pull request by salix5**
see https://github.com/Fluorohydride/ygopro-core/pull/488

### CODE REVIEW

**Comment by chronogenexx** [comment]
when player would synchro summon _Cyber Slash Harpie Lady_, _Nirvana High Paladin_ or _Ib the World Chalice Justiciar_, 百檎トークン cannot be treated as tuner(these cards don't use `aux.Tuner`).

**Comment by salix5** [comment]
圖片
[test_apple2.zip](https://github.com/Fluorohydride/ygopro-scripts/files/10712967/test_apple2.zip)

done
Thank you!

**Comment by mercury233** [comment]
confirming

**Comment by salix5** [comment]
Can we merge this PR?

**Pull request merged**
