### PR TITLE
fix Aslla piscu

### PR DESCRIPTION
**Pull request by nekrozar**
Fix this: If Aslla piscu Tributed by cost, Aslla piscu doesn't activate.

### CODE REVIEW

**Comment by DailyShana** [comment]
detail?

**Comment by nekrozar** [comment]
I was Tributed Aslla piscu to activate Nightmare Archfiends.
But Aslla piscu doesn't activate.

**Comment by DailyShana** [comment]
no problem, even on Japanese version

**Comment by nekrozar** [comment]
I confirmed that Aslla piscu activated.

**Pull request closed without merging**
