### PR TITLE
fix 灰流うらら. 屋敷わらし, 閉ザサレシ世界ノ冥神

### PR DESCRIPTION
**Pull request by salix5**
@mercury233 
Problem
Like other categories, Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,...) should be set only when the effect will sp_summon in mandatory part.

Current behavior
In order to check the conditions of effects like 灰流うらら/Ash Blossom & Joyous Spring, sp_summon in optional parts are logged as
Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,0,tp,LOCATION_DECK+LOCATION_HAND)
(tg=nil, count=0)

However, if a card has an effect that sp_summon some cards  in the mandatory part and sp_summon other cards in the optional part, this definition will conflict with the original definition.

Ex.
使神官－アスカトル/Ascator, Dawnwalker
sp_summon itself, can sp_summon from Deck
Now:
Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,e:GetHandler(),1,tp,LOCATION_DECK+LOCATION_HAND)

超量要請アルファンコール/Super Quantal Alphancall Appeal
sp_summon 1 monster from Extra Deck, can sp_summon from Deck
Now:
Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,1,tp,LOCATION_EXTRA)

Suppose that there are 2 effects.
Effect A:
sp_summon X from hand, then sp_summon 1 monster from Grave

Effect B:
sp_summon X from hand, then you can sp_summon 1 monster from Grave

It is difficult to distinguish A from B in current settings.

Solution
CATEGORY_DECKDES
Effects that include "Send a card from the Deck to the GY" or "Special Summon from the Deck".
(for 灰流うらら/Ash Blossom & Joyous Spring)

CATEGORY_GRAVE_SPSUMMON
Effects that include "Special Summon a Monster Card(s) from the GY" in the optional part.
(for 閉ザサレシ世界ノ冥神, 屋敷わらし/Ghost Belle & Haunted Mansion)

CATEGORY_GRAVE_ACTION
Effects that include "moving a card (other than Special Summon) from the GY" in the optional part.
(for 屋敷わらし/Ghost Belle & Haunted Mansion)

Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,...)
For "Special Summon from the Grave":
In order to keep 王家の眠る谷－ネクロバレー/Necrovalley work properly, 
it is set only when the effect will sp_summon or move cards from grave in mandatory part.
("Special Summon or Send to Hand" in mandatory part will set the info.)

Otherwise:
It is set only when the effect will certainly sp_summon in mandatory part.
("Special Summon or Send to Hand" in mandatory part will not set the info.)

### CODE REVIEW

**Comment by mercury233** [comment]
there still be many `Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,0` in other scripts, should them be updated?
image

**Comment by salix5** [comment]
I think yes.
Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,...) should be set only when the effect will sp_summon in mandatory part.

**Comment by salix5** [comment]
@mercury233 
Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,nil,0  is updated.
Thank you!

**Comment by salix5** [comment]
@mercury233 
Is there any problem in this branch?

**Pull request merged**
