### PR TITLE
update Duel.SSet

### PR DESCRIPTION
**Pull request by mercury233**
for https://github.com/Fluorohydride/ygopro-core/pull/248

### CODE REVIEW

**Comment by nekrozar** [comment]
You forget _Abyss Actor - Superstar_.

**Comment by mercury233** [comment]
i think it should do confirm, the original script forgot

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-scripts/blob/master/c25629622.lua#L103

**Comment by mercury233** [comment]
sorry i didn't see that, fixed

**Pull request merged**
