### PR TITLE
Better Nirvana check

### PR DESCRIPTION
**Pull request by Aephiex**
Procedure:
1. Use the effect of "Hundred Eyes Dragon" to copy "Phantom King Hydride" in my graveyard.
2. Pendulum summon "Double Resonator" and "Metalfoes Steelen".
3. Use the effect of "Double Resonator" to turn "Hundred Eyes Dragon" into tuner.
4. Use "Metalfoes Steelen" and "Hundred Eyes Dragon" to synchro summon "Nirvana High Paladin".

Issue:
In this situation, there is at least one tuner has been chosen for synchro material, so "Nirvana High Paladin" won't get that flag effect. Also, there is no pendulum summoned pendulum-tuners has been chosen for synchro material, so "Nirvana High Paladin" won't have it's label set to 1. Afterall, "Nirvana High Paladin" will strangely unable to salvage card.

After:
"Metalfoes Steelen" is a pendulum sommoned pendulum monster. Each of the other synchro material(s) is a synchro monster that can be used as a non-tuner synchro material. In this situation, "Nirvana High Paladin" will be able to salvage anyway.

### CODE REVIEW

**Comment by Aephiex** [comment]
Nirvana's material condition: 1 tuner + 1 or more non-tuner synchro monsters, where a pendulum summoned non-tuner monster can be used as though it's a tuner.

"Metalfoes Steelen" is pendulum summoned here. "Hundred Eyes Dragon" is now a tuner with the effect of "Phantom King Hydride" (EFFECT_NONTUNER). Tell me why doesn't Nirvana salvage.

**Comment by mercury233** [comment]
> このカードがＰ召喚したＰモンスターをチューナーとしてＳ召喚に成功した場合
> If this card is Synchro Summoned using a Pendulum Summoned Pendulum Monster Tuner
> 这张卡用灵摆召唤的灵摆怪兽为调整作同调召唤成功的场合

The tuner should be the P monster.

**Comment by Aephiex** [comment]
"Metalfoes Steelen" is a pendulum monster bro.

**Comment by mercury233** [comment]
But the tuner here is "Hundred Eyes Dragon".

**Comment by mercury233** [comment]
Sorry I never thought this.
_But I'm still in doubt with what will happen if we replace the Metalfoes with a _Clear Wing Fast Dragon_ whose level become 2..._

**Comment by Aephiex** [comment]
Both of them can be used as tuner or non-tuner. If I choose the tuner randomly, there is a 50% chance that you won't get that effect. In this situation, my script will always tells that you can use the effect. Note that that effect is optional, so if you don't want to activate it, just don't.

**Pull request merged**
