### PR TITLE
add EFFECT_EXTRA_LINK_COUNT

### PR DESCRIPTION
**Pull request by nekrozar**
Update this: Deal with _Salamangreat Sanctuary_.

### CODE REVIEW

**Comment by DailyShana** [comment]
use `EFFECT_TYPE_GRANT` to register a new link procedure to _Salamangreat_ link monster in extra.

**Comment by mercury233** [comment]
will `mg:getcount()>=2 or (duel.isplaaleraffectedbyeffect(xxx) and mg:getcount()==1 and mg:gefirst():issetcard(xxx))` work?

**Comment by DailyShana** [comment]
sample
```
function c10000.initial_effect(c)
    --
    local e3=Effect.CreateEffect(c)
    e3:SetDescription(aux.Stringid(10000,0))
    e3:SetType(EFFECT_TYPE_FIELD)
    e3:SetCode(EFFECT_SPSUMMON_PROC)
    e3:SetProperty(EFFECT_FLAG_UNCOPYABLE+EFFECT_FLAG_IGNORE_IMMUNE)
    e3:SetRange(LOCATION_EXTRA)
    e3:SetCondition(c10000.linkcon)
    e3:SetOperation(c10000.linkop)
    e3:SetValue(SUMMON_TYPE_LINK)
    local e4=Effect.CreateEffect(c)
    e4:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
    e4:SetRange(LOCATION_MZONE) 
    e4:SetTargetRange(LOCATION_EXTRA,0)
    e4:SetTarget(aux.TargetBoolFunction(Card.IsType,TYPE_LINK))--and IsSetCard(0x???)
    e4:SetLabelObject(e3)
    c:RegisterEffect(e4)
end
function c10000.lmfilter(c,lc)
    return c:IsFaceup() and c:IsCanBeLinkMaterial(lc) and c:IsCode(lc:GetCode())
end
function c10000.linkcon(e,c)
    if c==nil then return true end
    local tp=c:GetControler()
    return Duel.IsExistingMatchingCard(c10000.lmfilter,tp,LOCATION_MZONE,0,1,nil,c)
end
function c10000.linkop(e,tp,eg,ep,ev,re,r,rp,c)
    local mg=Duel.SelectMatchingCard(tp,c10000.lmfilter,tp,LOCATION_MZONE,0,1,1,nil,c)
    c:SetMaterial(mg)
    Duel.SendtoGrave(mg,REASON_LINK)
end
```

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-pre-script/commit/fe8c8746ffedee0169c96f84d92fb8a1372295ca
Added. Thank you!

**Pull request closed without merging**
