### PR TITLE
update fusion spell check

### PR DESCRIPTION
**Pull request by mercury233**
fix https://github.com/Fluorohydride/ygopro-scripts/pull/1244#issuecomment-554725326
require https://github.com/Fluorohydride/ygopro-scripts/pull/1286

### CODE REVIEW

**Comment by edo9300** [comment]
This is wrong, with the available rulings, you have to use (in case of red eyes fusion) the "red-eyes" monster as the listed "red-eyes" monster, it's not enough having a red-eyes in the mats

**Comment by mercury233** [comment]
@edo9300 take Slash Dragon for example, it do check the fusion material contain a red-eye B dragon and a warrior, and the 2 cards must be different

**Comment by edo9300** [comment]
Hmm, I'm not a fan of this approach, as it's very specific, _but it seems to work_ anyways, it's not only red eyes fusion that has to be updated, miracle synchro fusion should as well, and iirc there are other similar cards that fall under that category.

**Comment by mercury233** [comment]
I found that we only need to update those fusion monsters: The designated part of material can be replaced, and the rest part can also match the requirement of the fusion spell.

**Pull request merged**
