### PR TITLE
update ドラグニティアームズ－グラム

### PR DESCRIPTION
**Pull request by SmileEmoticon**

### CODE REVIEW

**Comment by mercury233** [comment]
what will this fix?

**Comment by SmileEmoticon** [comment]
it should be added since arma gram change the ATK stats of a monster along with disable effect

**Comment by mercury233** [comment]
will it affect anything actually?

**Comment by SmileEmoticon** [comment]
i am not sure

**Comment by mercury233** [comment]
There do be a problem, if this card equip a monster by its 3rd effect and use its 2nd effect to disable itself, the equipped monster will be destroyed and it shouldn't count in the amount of equip cards to down the attack.
But `Duel.AdjustInstantly` won't fix this.

**Pull request closed without merging**
