### PR TITLE
fix & update pendulum summon for Pendulum Encore

### PR DESCRIPTION
**Pull request by 465uytrewq**
https://github.com/Fluorohydride/ygopro-core/pull/390

### CODE REVIEW

**Comment by mercury233** [comment]
will be checked after the ocg ruling of this card come out

**Comment by purerosefallen** [comment]
Could you tell me what the `chk` is?

**Comment by chronogenexx** [comment]
Sorry, i was too late.
@purerosefallen updated https://github.com/Fluorohydride/ygopro-core/pull/390/commits/43f31aa1ef942f981b00914d8906fd83eea6de34 and https://github.com/Fluorohydride/ygopro-scripts/pull/1681/commits/1f4bb67497e42f62a884b0c8a88b1c31f408275e.

**Comment by purerosefallen** [comment]
Have an explain of every function in core you added.

In addition, don't use word `PSummon` for function name, but use phrase `PendulumSummon` instead.

**Comment by chronogenexx** [comment]
https://github.com/Fluorohydride/ygopro-core/pull/390/commits/633960fd9545149fbe9c61b59ae5fa53ad28ee79 https://github.com/Fluorohydride/ygopro-scripts/pull/1681/commits/642555996f2d6302e84957065db9b469a52a35be renamed.

> @purerosefallen 
> Have an explain of every function in core you added.

update https://github.com/Fluorohydride/ygopro-core/pull/390#issue-694298440 . read this.

**Pull request closed without merging**
