### PR TITLE
add Auxiliary.AddContactFusionProcedure

### PR DESCRIPTION
**Pull request by purerosefallen**

### CODE REVIEW

**Comment by nekrozar** [comment]
_Elder Entity N'tss_'s `EFFECT_SPSUMMON_PROC` is remaining.

**Comment by purerosefallen** [comment]
@nekrozar Some cards are too hard to change. So I kept some.

**Comment by nekrozar** [comment]
move https://github.com/Fluorohydride/ygopro-scripts/pull/1173.
However this commit should need change in `Auxiliary.ContactFusionMaterialFilter`.

After:
```lua
function Auxiliary.ContactFusionMaterialFilter(c,fc,filter)
	return c:IsCanBeFusionMaterial(fc,SUMMON_TYPE_SPECIAL) and (not filter or filter(c,fc))
end
```

**Comment by purerosefallen** [comment]
@nekrozar Changes were made for the above PR.
But for other contact fusions still using EFFECT_SPSUMMON_PROC, please change them in the above PR.

**Comment by nekrozar** [comment]
@purerosefallen Thank you for merge!

**Pull request merged**
