### PR TITLE
update Link In-Flyer

### PR DESCRIPTION
**Pull request by nekrozar**
https://github.com/Fluorohydride/ygopro-core/pull/109

### CODE REVIEW

**Comment by purerosefallen** [comment]
But i think the value of spsummon procs are the summon type. Eg. SUMMON_TYPE_XYZ
So how to deal with that?

**Comment by nekrozar** [comment]
`SUMMON_TYPE` is used 0x1000000 or higher.

**Comment by purerosefallen** [comment]
However, some cards use a number below that as a summon type. eg. Gladiator Beasts

**Comment by purerosefallen** [comment]
Maybe you need to use 0xff as the zones and the number above 0x100 as the summon type. So you would have to change the Gladiator Beast scripts

**Comment by nekrozar** [comment]
https://github.com/Fluorohydride/ygopro-core/blob/master/operations.cpp#L2460
`EFFECT_SPSUMMON_PROC` don't read from 0x10000 to 0xff0000.

**Comment by purerosefallen** [comment]
Well, thats ok.
And could you update EFFECT_SPSUMMON_PROC_G as well?

**Comment by purerosefallen** [comment]
And.. Using *0x1000 seems a little bit ugly. Could you change it into bit.lshift?

**Comment by nekrozar** [comment]
>And could you update EFFECT_SPSUMMON_PROC_G as well?

`EFFECT_SPSUMMON_PROC_G` is used Pendulum Summon only.
So I think unnecessary.

>Could you change it into bit.lshift?

https://github.com/Fluorohydride/ygopro-scripts/pull/912/commits/633eca893ca9125729acfd8f82c4582a979d5c90 Updated.

**Pull request merged**
