### PR TITLE
add Auxiliary.AddEquipSpellEffect

### PR DESCRIPTION
**Pull request by salix5**
@mercury233 
@purerosefallen 
@465uytrewq 

```lua
---Add EFFECT_TYPE_ACTIVATE effect to Equip Spell Cards without operation
---@param c Card
---@param is_self boolean
---@param is_opponent boolean
---@param filter function
---@param eqlimit function|nil
---@param condition? function
function Auxiliary.AddEquipSpellEffect(c,is_self,is_opponent,filter,eqlimit,condition)
```
filter: target filter of EFFECT_TYPE_ACTIVATE 
eqlimit: EFFECT_EQUIP_LIMIT value

### CODE REVIEW

**Comment by 465uytrewq** [comment]
it might be better to update that can use by _Scroll of Bewitchment_, _Armed Changer_ and so on.

**Comment by salix5** [comment]
@465uytrewq 
Do you mean add custom cost/target?
Thank you.

**Comment by 465uytrewq** [comment]
_Psychic Blade_, _Evil Eye of Gorgoneio_, _Mikanko Reflection Rondo_ have "You can only activate 1 ○○ per turn" text.
`Auxiliary.AddEquipSpellEffect` should return `e1`.

e.g.
```lua
--utility.lua
---Add EFFECT_TYPE_ACTIVATE effect to Equip Spell Cards without operation
---@param c Card
---@param is_self boolean
---@param is_opponent boolean
---@param filter function
---@param eqlimit function|nil
---@param pause? boolean
---@param skip_target? boolean
function Auxiliary.AddEquipSpellEffect(c,is_self,is_opponent,filter,eqlimit,pause,skip_target)
	local value=(type(eqlimit)=="function") and eqlimit or 1
	if pause==nil then pause=false end
	if skip_target==nil then skip_target=false end
	--Activate
	local e1=Effect.CreateEffect(c)
	e1:SetCategory(CATEGORY_EQUIP)
	e1:SetType(EFFECT_TYPE_ACTIVATE)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET+EFFECT_FLAG_CONTINUOUS_TARGET)
	if not skip_target then
		e1:SetTarget(Auxiliary.EquipSpellTarget(is_self,is_opponent,filter,eqlimit))
	end
	e1:SetOperation(Auxiliary.EquipSpellOperation(eqlimit))
	if not pause then
		c:RegisterEffect(e1)
	end
	--Equip limit
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetCode(EFFECT_EQUIP_LIMIT)
	e2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e2:SetValue(value)
	c:RegisterEffect(e2)
	return e1
end

--サイコ・ブレイド
function c75539614.initial_effect(c)
	--Activate
	local e1=aux.AddEquipSpellEffect(c,true,true,Card.IsFaceup,nil,true)
	e1:SetCountLimit(1,75539614+EFFECT_COUNT_CODE_OATH)
	e1:SetCost(c75539614.cost)
	c:RegisterEffect(e1)
	--atk/def
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_EQUIP)
	e2:SetCode(EFFECT_UPDATE_ATTACK)
	e2:SetValue(c75539614.val)
	c:RegisterEffect(e2)
	local e3=e2:Clone()
	e3:SetCode(EFFECT_UPDATE_DEFENSE)
	c:RegisterEffect(e3)
end

--幻惑の巻物
function c10352095.initial_effect(c)
	--Activate
	local e1=aux.AddEquipSpellEffect(c,true,true,Card.IsFaceup,nil,true,true)
	e1:SetTarget(c10352095.target)
	c:RegisterEffect(e1)
	--ATTRIBUTE
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_EQUIP)
	e2:SetCode(EFFECT_CHANGE_ATTRIBUTE)
	e2:SetCondition(c10352095.con)
	e2:SetValue(c10352095.value)
	c:RegisterEffect(e2)
	e1:SetLabelObject(e2)
end
```

**Comment by salix5** [comment]
done
Thank you!

**Comment by salix5** [comment]
@465uytrewq
Is there anything need to change?

**Pull request merged**
