### PR TITLE
Update c22423493.lua

### PR DESCRIPTION
**Pull request by KoishiMint**
Fixed an issue against Burning Abyss monsters.

### CODE REVIEW

**Comment by mercury233** [comment]
好像还有其他几张卡有这个问题来着`_(:з」∠)_`

**Comment by KoishiMint** [comment]
那我再找找。

**Comment by KoishiMint** [comment]
All cards with similar effects have been fixed.

**Comment by purerosefallen** [comment]
i doubt if `ec:GetLinkedZone(pp) & 0x1 << c:GetPreviousSequence()~=0` returns strange things. i think brackets are needed.

**Comment by KoishiMint** [comment]
np because of operator precedence

**Pull request merged**
