### PR TITLE
Fix "Power Wall"

### PR DESCRIPTION
**Pull request by Lyris12**
Interaction between "Power Wall" & "Blue-Eyes Chaos MAX Dragon"

### CODE REVIEW

**Comment by DailyShana** [comment]
we can't change in this way, if the cards sent to grave have "if this card is sent to graveyard" effect, such effect will be activated in the wrong timing

**Comment by Lyris12** [comment]
Well, currently, **8** cards (instead of 16) are discarded from the Deck with "Power Wall" to reduce **8000** piercing battle damage from "Blue-Eyes Chaos MAX Dragon" to 0. Is there another way to correct this interaction?

**Comment by DailyShana** [comment]
I know what you are fixing but currently it's hard to resolve it

**Comment by edo9300** [comment]
@DailyShana they way we fixed that on percy is by using external functions to set/retrieve the battle damage instead of erlying on the argument pased in the effect, the issue here is that all th effects are raised at teh same time, all with teh same value, so that remains the same when resolving all the related effects

**Comment by DailyShana** [comment]
@edo9300 thank you for you advise. I plan to update EFFECT_PIERCE to support double pierce damage

**Pull request closed without merging**
